In [ ]:
import numpy as np

ReLU(Rectified Linear Unit(Hidden Layer))

In [ ]:
def relu(x):
  return np.maximum(0,x)
relu(10)


np.int64(10)

In [ ]:
relu(-10)

np.int64(0)

In [ ]:
relu(np.array([10,-10,100]))

array([ 10,   0, 100])

Leaky_relue(Hidden layer)

In [ ]:
def leaky_relu(x,alpha=0.01):
  return np.where(x>0,x,alpha*x)


leaky_relu(-1)

array(-0.01)

In [ ]:
leaky_relu(-5)

array(-0.05)

In [ ]:
leaky_relu(np.array([10,-10,100]))

array([ 10. ,  -0.1, 100. ])

ElU Exponential Linear Unit(Hidden Layer)

In [ ]:
def elu(x,alpha=1.0):
  return np.where(x>0,x,alpha*(np.exp(x)-1))

elu(5)

array(5.)

In [ ]:
elu(np.array([10,-10,100]))

array([ 10.       ,  -0.9999546, 100.       ])

Sigmoid(Output layer & binarryClass problem)

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

sigmoid(-1)

np.float64(0.2689414213699951)

In [ ]:
sigmoid(np.array([10,-10,100]))

array([9.99954602e-01, 4.53978687e-05, 1.00000000e+00])

Softmax (Output layer & Multiclass problem)

In [ ]:
def softmax(x):
  e_x = np.exp(x-np.max(x))
  return e_x/np.sum(e_x,axis=0)

proba = softmax(np.array([2,1,.5]))
proba

array([0.62853172, 0.2312239 , 0.14024438])

In [ ]:
sum(proba)

np.float64(1.0)

Swish(Hidden Layer)
Swish is a self gated activation function

In [ ]:
def swish(x,beta=1.0):
  return x*sigmoid(beta*x)
swish(5)

np.float64(4.966535745378576)

In [ ]:
swish(np.array([10,-10,100]))

array([ 9.99954602e+00, -4.53978687e-04,  1.00000000e+02])

Linear (Output layer)




In [ ]:
def linear(x):
  return x
linear(5)

5

In [ ]:
linear(np.array([10,-10,100]))

array([ 10, -10, 100])

Tanh (Hyperbolic Tangent)

In [ ]:
def tanh(x):
  return (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))

tanh(10)

np.float64(0.9999999958776926)

In [ ]:
tanh(10)

np.float64(0.9999999958776926)